### ISSUE TITLE
low performance for First phase

### ISSUE THREAD

**Issue by jianlong-yuan** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#1]
Train the SIM model:

python train_sim.py

I have finished 200000 iters, but the performance is much lower.
![image](https://user-images.githubusercontent.com/18137551/86559843-8ae95f00-bf8f-11ea-8b02-22eb9b12f2fc.png)

Could you help me? Thank you.

**Comment by Zhonghao2016** [comment]
Please use the CycleGAN transferred source images which can be downloaded at [GTA5](https://drive.google.com/file/d/1OBvYVz2ND4ipdfnkhSaseT8yu2ru5n5l/view). Current methods attacking the semantic segmentation UDA problem fall into three sub-divisions: the image-level transferring, the feature-level transferring and the label-level transferring. In our case, we focus on the latter two, so we simply utilize the CycleGAN transferred source images for the image-level adaptation.

**Comment by dh23333** [comment]
I used the dataset SNYTHIA and cityscapes, but only got the average mIOU: 34.61.
![image](https://user-images.githubusercontent.com/35715068/86566017-7f039a00-bf9b-11ea-80fe-6174a2810633.png)
Is it convenient for you to remind me about the solution of this problem? Is there any pre-process needed which I ignored?

**Comment by Zhonghao2016** [comment]
You can download the CycleGAN transferred SYNTHIA dataset at [SYNTHIA](https://drive.google.com/file/d/1d7GxVhyN8HzEIPDeRIB3dRXTYzHI91ng/view).

**Comment by jianlong-yuan** [comment]
For the first stage, i downloded your dataset, and got 45.23 mIoU. It is also different from your 46.2. I have finished 9w, and got the best model at 7.5w

**Comment by Zhonghao2016** [comment]
Please refer to Fig. 2 of our [paper](https://arxiv.org/pdf/2003.08040.pdf). The model of the best performance occurs at around 145K iterations. Therefore, to attain the optimal performance, please finish the whole training process which is 200K iterations and then go ahead for the test process. Please let me know if there is any other problems.

**Comment by jianlong-yuan** [comment]
Ok, thank you.
