### ISSUE TITLE
the clsDiscriminator and infoDiscriminator in ./model/discriminator.py

### ISSUE THREAD

**Issue by Lufei-github** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#2]
Firstly,thank you for sharing this wonderful code!
I find the adversarial loss is very unstable because of the global alignment in the segmentation output,and you provide a good solution to solve this problem.By chance,I saw your discriminator.py has three Discriminators.And you only use the FCDiscriminator.But for what consideration you write clsDiscriminator and infoDiscriminator?

**Comment by Zhonghao2016** [comment]
Thanks for your interests in our work. The clsDiscriminator and infoDiscriminator were place holders and I forgot to clear up them when releasing the code. Thanks for raising this issue.
