### ISSUE TITLE
SSL.py

### ISSUE THREAD

**Issue by Lufei-github** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#3]
Line 139 of your SSL.py,label[(prob<thres[i]) * (label==i)] = 255.
This line means that  we ignore the prediction that are lower than thres[i],but what about the predictions that are higher than thres[i]?Are we just keep their prediction value?
Because in my opinion,the predictions that are higher than thres[i] should be to 1,so can you give me a definite answer.Thanks so much!

**Comment by Zhonghao2016** [comment]
Hi! The SSL.py file generates the pseudo-labels for confident pixel predictions. Here, ```thre[i]``` is exactly the confidence threshold for class ```i```. If the probability for the label prediction of a pixel is higher than that threshold, the pseudo-label is then generated for that pixel (label ```i```); however, if not, the pseudo-label is not generated so we set an ignore label (label ```255```) for that pixel.

**Comment by Lufei-github** [comment]
I understand now!Thanks so much!
