### ISSUE TITLE
the function of global_avg_pool

### ISSUE THREAD

**Issue by dh23333** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#4]
![image](https://user-images.githubusercontent.com/35715068/87953419-98e5c680-cadd-11ea-8a3a-8547ecf20493.png)

Is this function used to average the features belonging to the same background semantic class? So, if the batch size>1, will weight.expand be wrong?

**Comment by Zhonghao2016** [comment]
Hi! Yes, this function is used for averaging the intra-class feature vectors of background stuff and foreground instances. And yes, it may pose some problems if batch size is greater than 1. If the batch size is fixed to 1 (which should be the case to fit the model into a GPU), there won't be any issues.

**Comment by dh23333** [comment]
Thank you very much~
