### ISSUE TITLE
Question about gta5_deeplab.zip

### ISSUE THREAD

**Issue by zengkaiwei** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#5]
When I run "train_sim.py":
No such file or directory: './data/gta5_deeplab\\labels/15564.png'

The original GTA5 dataset has two files: images and labels, but the The gta5_deeplab.zip you given only have the "image" file. Canyou tell me where is the label?

**Comment by Zhonghao2016** [comment]
Hi! Thanks for raising this issue. I just modified the instructions. You can now download the labels from the link provided in the instructions.
