### ISSUE TITLE
SSL - found a bug

### ISSUE THREAD

**Issue by BinhuiXie** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#6]
https://github.com/SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment/blob/fd3d0b081be1e5309b3348fb29e5d253cdb9984f/SSL.py#L132

> If the media confidence value is below 0.9, then the confidence threshold for that class is set to the median confidence value; otherwise, it is set to 0.9. (ref. original paper)

Hello, thank for sharing the great work. Here, I have a quick question. When the median confidence value is above 0.9, the threshold is set to 0.9. Thus there are more than half of pseudo-labels with respect to easy-to-transfer classes, and it will tend to be biased towards these classes ignoring other classes.

**Comment by Zhonghao2016** [comment]
Hi! Thanks for your question. Consider pixels belonging to sky or road are more than pixels belonging to signs or lights across the dataset. The pixel numbers corresponding to different classes vary themselves. I think that the unbalanced class problem is a common issue not only for the segmentation task but also for the classification and other vision tasks. Regarding your question, the threshold 0.9 is an empirical value to allow more confident pixels to have pseudo labels. Even if we don't bound the median confidence value, there can still be the class unbalance problem. In summary, the median confidence threshold is a minor cause to the class unbalance problem compared to the dataset inherent unbalance of pixels belonging to different classes.

**Comment by BinhuiXie** [comment]
Thank you for your response! I will add to this thread if I have any more questions. For now, I am closing the issue.
