### ISSUE TITLE
Are there any skills for training GAN？

### ISSUE THREAD

**Issue by dh23333** [SHI-Labs/Unsupervised-Domain-Adaptation-with-Differential-Treatment#7]
Sorry... I ran the code on other dataset but got poor performance. I guess it may be because the parameters have not been adjusted properly. So is it convient for you to give me some tips of training GAN？

**Comment by Zhonghao2016** [comment]
Sorry, I'm not able to answer questions specifically to your applications. However, you could search some useful GAN training tips  online. Thanks!
